services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/restapi
      - SPRING_DATASOURCE_USERNAME=amalireda
      - SPRING_DATASOURCE_PASSWORD=amalireda
      # - SPRING_SQL_INIT_MODE=always
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_JWT_SECRET_KEY=4iSpEg/EnSthq/CkF5qk0x049yVUrCS5A1h+yCOPrqNi+MElXyKr2WitOA0KhrMS
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=restapi
      - POSTGRES_USER=amalireda
      - POSTGRES_PASSWORD=amalireda
    volumes:
      - ./init-db-spring-schema.sql:/docker-entrypoint-initdb.d/init-db-spring-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U amalireda -d restapi"]
      interval: 10s
      timeout: 5s
      retries: 5