services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/restapi
      - SPRING_DATASOURCE_USERNAME=amalireda
      - SPRING_DATASOURCE_PASSWORD=amalireda
      - SPRING_SQL_INIT_MODE=always
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=restapi
      - POSTGRES_USER=amalireda
      - POSTGRES_PASSWORD=amalireda
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U amalireda -d restapi"]
      interval: 10s
      timeout: 5s
      retries: 5